### PR TITLE
Fix/31/replace the use of grace for tableflip

### LINKED ISSUE #31: Replace the use of `github.com/facebookgo/grace`
github.com/facebookarchive/grace is deprecated. It should be replaced. From what I remember, this is the same as github.com/cloudflare/tableflip used in git-repository-core, but this is yet to be confirmed.

### PR DESCRIPTION
**Pull request by sc-zenokerr**
# Replace grace with [Scalingo/go-utils/graceful](https://github.com/Scalingo/go-utils/tree/master/graceful)

Fix #31 

Upgrade go version to 1.22.4

### CODE REVIEW

File: cmd/acadock-monitoring/main_test.go [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+			t.Log(output)
+			require.Equal(t, 1, strings.Count(output, "parent exited"))
+			require.Zero(t, strings.Count(output, "upgrade requested"))
+			require.Zero(t, strings.Count(output, "upgrade failed"))
+		})
+	}
+}
+
+func TestService_Restart(t *testing.T) {
+	// Set some environment variables
```
Comment (ipfaze) [inline cmd/acadock-monitoring/main_test.go:75]: issue(blocking): please add some `t.Run(...)` with a message explaining what behavior is expected.
For example:
```go
t.Run("it restarts when signal SIGHUP is sent")
```

File: cmd/acadock-monitoring/main_test.go [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+
+	// Check the output
+	output := isGraceful.GetOutput()
+	t.Log(output)
+	require.Equal(t, 1, strings.Count(output, "upgrade requested"))
+	require.Zero(t, strings.Count(output, "upgrade failed"))
+}
+
+func TestService_Restart_Twice(t *testing.T) {
+	// Set some environment variables
```
Comment (ipfaze) [inline cmd/acadock-monitoring/main_test.go:114]: issue(blocking): same as before, please add some `t.Run(...)` with a message explaining what behavior is expected.

File: cmd/acadock-monitoring/main_test.go [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+
+func TestService_Shutdown(t *testing.T) {
+	// Set some environment variables
+	upgradeTimeout := time.Millisecond * 200
+	shutdownTimeout := time.Millisecond * 100
+	t.Setenv("GRACEFUL_UPGRADE_TIMEOUT", upgradeTimeout.String())
+	t.Setenv("GRACEFUL_SHUTDOWN_TIMEOUT", shutdownTimeout.String())
+
+	for _, s := range []os.Signal{syscall.SIGINT, syscall.SIGTERM} {
+		t.Run("Signal "+s.String(), func(t *testing.T) {
```
Comment (ipfaze) [inline cmd/acadock-monitoring/main_test.go:38]: issue(blocking): the `t.Run(...)` message seems not to explain what behavior is expected.
Can you make it clearer please.

File: cmd/acadock-monitoring/isgraceful/isgraceful.go [hunk 4]
```diff
@@ -0,0 +1,225 @@
...
+	"bytes"
+	"errors"
+	"io"
+	"os"
+	"os/exec"
+	"strconv"
+	"strings"
+	"sync"
+	"syscall"
+	"testing"
```
Comment (ipfaze) [inline cmd/acadock-monitoring/isgraceful/isgraceful.go:13]: question: It seems weird to me to have the `testing` package within a go file which is not for testing purpose.
Are you sure of what you made here?

File: cmd/acadock-monitoring/main.go [hunk 5]
```diff
@@ -59,7 +63,7 @@ func main() {
 		filters.WithAverageConfig(config.QueueLengthPointsPerSample, config.QueueLengthSamplingInterval),
 	)
 	if err != nil {
-		panic(err)
+		log.Fatalln(err)
```
Comment (ipfaze) [inline cmd/acadock-monitoring/main.go:66]: question: Why use `log.Fatalln` here rather than `panic`?

**Review by ipfaze — CHANGES_REQUESTED** [review]

File: cmd/acadock-monitoring/main_test.go (hunk 3 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/main_test.go:38]: I can make this clearer, sure. Just so you know, this message is similar to that in go-utils/graceful/service_test.go:36

File: cmd/acadock-monitoring/main_test.go (hunk 1 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/main_test.go:75]: Question. I can understand the need for a more detailed explanation of the test, but the use of "t.Run" is normally for subtests. Is it our pattern to use t.Run even if there is only one test in the group?

File: cmd/acadock-monitoring/main_test.go (hunk 2 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/main_test.go:114]: Given this is the same comment.

I'll merge the two "Restart" tests together into one parent test, and use "t.Run" to treat them as sub tests.

File: cmd/acadock-monitoring/isgraceful/isgraceful.go (hunk 4 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/isgraceful/isgraceful.go:13]: The isgraceful/isgraceful.go is designed for testing.

It uses the same techniques employed in go-utils/graceful, but written in a re-useable way.

I wanted to discuss this with you. I think it would be worth having this moved to go-utils package, so it can be reused to test the graceful behaviour of our other services too (some do not have tests e.g. git-repository-core)

File: cmd/acadock-monitoring/main_test.go (hunk 1 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/main_test.go]: main_test.go removed

File: cmd/acadock-monitoring/main_test.go (hunk 3 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/main_test.go]: main_test.go removed

File: cmd/acadock-monitoring/isgraceful/isgraceful.go (hunk 4 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/isgraceful/isgraceful.go]: isgraceful removed

File: cmd/acadock-monitoring/main.go (hunk 5 above)
Comment (ipfaze) [reply cmd/acadock-monitoring/main.go:62]: No reason to leave it as `panic`, I was just asking by curiosity :slightly_smiling_face:

File: cmd/acadock-monitoring/isgraceful/isgraceful.go (hunk 4 above)
Comment (ipfaze) [reply cmd/acadock-monitoring/isgraceful/isgraceful.go]: > I wanted to discuss this with you. I think it would be worth having this moved to go-utils package, so it can be reused to test the graceful behaviour of our other services too (some do not have tests e.g. git-repository-core)

Did you talk about this to the team during my days-off? I think it would be great to discuss it with the team like you did for the signal capture :wink:

**Review by ipfaze — APPROVED** [review]
LGTM :+1:

File: cmd/acadock-monitoring/isgraceful/isgraceful.go (hunk 4 above)
Comment (sc-zenokerr) [reply cmd/acadock-monitoring/isgraceful/isgraceful.go]: I did not discuss it with the team, but I did do so with Leo.

It has been moved to go-utils/graceful package, but is not-exported. Leo was :+1: to replace the exiting test functions with it. In theory it could be exported, but there is no need for it at the moment.

We should add a ticket for the future to add a function to go-utils/graceful to ListenTCP. There is another SL service that uses tableflip to listenTCP. It would be good if it could use go-utils/graceful library instead.

This could be a ninja task.

Comment (ipfaze) [reply cmd/acadock-monitoring/isgraceful/isgraceful.go]: Really nice! :clap: 
If you want, you can create the issue related to this in the https://github.com/Scalingo/go-utils/issues to not forget about it.
And indeed, it will be a ninja task!
